// flow-typed signature: 631d251f3af0781f43d844f4eaab74c0
// flow-typed version: <<STUB>>/haul_v^1.0.0-beta.13/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'haul'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'haul' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'haul/bin/cli' {
  declare module.exports: any;
}

declare module 'haul/hot/index' {
  declare module.exports: any;
}

declare module 'haul/hot/patch' {
  declare module.exports: any;
}

declare module 'haul/src/cli' {
  declare module.exports: any;
}

declare module 'haul/src/cliEntry' {
  declare module.exports: any;
}

declare module 'haul/src/commands/bundle' {
  declare module.exports: any;
}

declare module 'haul/src/commands/init' {
  declare module.exports: any;
}

declare module 'haul/src/commands/reload' {
  declare module.exports: any;
}

declare module 'haul/src/commands/start' {
  declare module.exports: any;
}

declare module 'haul/src/errors' {
  declare module.exports: any;
}

declare module 'haul/src/hot/babelPlugin' {
  declare module.exports: any;
}

declare module 'haul/src/hot/client/hotApi' {
  declare module.exports: any;
}

declare module 'haul/src/hot/client/hotClient' {
  declare module.exports: any;
}

declare module 'haul/src/hot/client/hotPatch' {
  declare module.exports: any;
}

declare module 'haul/src/hot/client/importScriptsPolyfill' {
  declare module.exports: any;
}

declare module 'haul/src/hot/client/index' {
  declare module.exports: any;
}

declare module 'haul/src/hot/client/utils' {
  declare module.exports: any;
}

declare module 'haul/src/loaders/assetLoader' {
  declare module.exports: any;
}

declare module 'haul/src/logger' {
  declare module.exports: any;
}

declare module 'haul/src/messages/bundleBuilding' {
  declare module.exports: any;
}

declare module 'haul/src/messages/bundleBuilt' {
  declare module.exports: any;
}

declare module 'haul/src/messages/bundleFailed' {
  declare module.exports: any;
}

declare module 'haul/src/messages/checkingProject' {
  declare module.exports: any;
}

declare module 'haul/src/messages/commandFailed' {
  declare module.exports: any;
}

declare module 'haul/src/messages/commandNotImplemented' {
  declare module.exports: any;
}

declare module 'haul/src/messages/commandSuccess' {
  declare module.exports: any;
}

declare module 'haul/src/messages/editorNotConfigured' {
  declare module.exports: any;
}

declare module 'haul/src/messages/enterEntryFileName' {
  declare module.exports: any;
}

declare module 'haul/src/messages/generatedConfig' {
  declare module.exports: any;
}

declare module 'haul/src/messages/generatingConfig' {
  declare module.exports: any;
}

declare module 'haul/src/messages/gitAddedEntries' {
  declare module.exports: any;
}

declare module 'haul/src/messages/gitAddingEntries' {
  declare module.exports: any;
}

declare module 'haul/src/messages/gitAlreadyAdded' {
  declare module.exports: any;
}

declare module 'haul/src/messages/gitNotFound' {
  declare module.exports: any;
}

declare module 'haul/src/messages/haulCommandHelp' {
  declare module.exports: any;
}

declare module 'haul/src/messages/haulHelp' {
  declare module.exports: any;
}

declare module 'haul/src/messages/index' {
  declare module.exports: any;
}

declare module 'haul/src/messages/initialBundleInformation' {
  declare module.exports: any;
}

declare module 'haul/src/messages/initialStartInformation' {
  declare module.exports: any;
}

declare module 'haul/src/messages/invalidProject' {
  declare module.exports: any;
}

declare module 'haul/src/messages/overwriteConfig' {
  declare module.exports: any;
}

declare module 'haul/src/messages/selectEntryFile' {
  declare module.exports: any;
}

declare module 'haul/src/messages/sourceMapFileNotFound' {
  declare module.exports: any;
}

declare module 'haul/src/messages/sourceMapInvalidFormat' {
  declare module.exports: any;
}

declare module 'haul/src/messages/verifiedProject' {
  declare module.exports: any;
}

declare module 'haul/src/messages/webpackCompilerPlatformNotFound' {
  declare module.exports: any;
}

declare module 'haul/src/messages/webpackConfigNotFound' {
  declare module.exports: any;
}

declare module 'haul/src/resolvers/AssetResolver' {
  declare module.exports: any;
}

declare module 'haul/src/resolvers/HasteResolver' {
  declare module.exports: any;
}

declare module 'haul/src/server/assets/debuggerWorker' {
  declare module.exports: any;
}

declare module 'haul/src/server/index' {
  declare module.exports: any;
}

declare module 'haul/src/server/middleware/devToolsMiddleware' {
  declare module.exports: any;
}

declare module 'haul/src/server/middleware/hotMiddleware' {
  declare module.exports: any;
}

declare module 'haul/src/server/middleware/liveReloadMiddleware' {
  declare module.exports: any;
}

declare module 'haul/src/server/middleware/loggerMiddleware' {
  declare module.exports: any;
}

declare module 'haul/src/server/middleware/missingBundleMiddleware' {
  declare module.exports: any;
}

declare module 'haul/src/server/middleware/openInEditorMiddleware' {
  declare module.exports: any;
}

declare module 'haul/src/server/middleware/rawBodyMiddleware' {
  declare module.exports: any;
}

declare module 'haul/src/server/middleware/requestChangeMiddleware' {
  declare module.exports: any;
}

declare module 'haul/src/server/middleware/statusPageMiddleware' {
  declare module.exports: any;
}

declare module 'haul/src/server/middleware/symbolicateMiddleware' {
  declare module.exports: any;
}

declare module 'haul/src/server/middleware/systraceMiddleware' {
  declare module.exports: any;
}

declare module 'haul/src/server/util/WebsocketDebuggerProxy' {
  declare module.exports: any;
}

declare module 'haul/src/server/util/websocketProxy' {
  declare module.exports: any;
}

declare module 'haul/src/types' {
  declare module.exports: any;
}

declare module 'haul/src/utils/exec' {
  declare module.exports: any;
}

declare module 'haul/src/utils/findProvidesModule' {
  declare module.exports: any;
}

declare module 'haul/src/utils/fixRequireIssues' {
  declare module.exports: any;
}

declare module 'haul/src/utils/getBabelConfig' {
  declare module.exports: any;
}

declare module 'haul/src/utils/getCompilerByPlatform' {
  declare module.exports: any;
}

declare module 'haul/src/utils/getEntryFiles' {
  declare module.exports: any;
}

declare module 'haul/src/utils/getReactNativeVersion' {
  declare module.exports: any;
}

declare module 'haul/src/utils/getWebpackConfig' {
  declare module.exports: any;
}

declare module 'haul/src/utils/haulPortHandler' {
  declare module.exports: any;
}

declare module 'haul/src/utils/haulProgressBar' {
  declare module.exports: any;
}

declare module 'haul/src/utils/makeReactNativeConfig' {
  declare module.exports: any;
}

declare module 'haul/src/utils/polyfillEnvironment' {
  declare module.exports: any;
}

declare module 'haul/src/utils/resolveModule' {
  declare module.exports: any;
}

declare module 'haul/vendor/polyfills/Array.es6' {
  declare module.exports: any;
}

declare module 'haul/vendor/polyfills/Array.prototype.es6' {
  declare module.exports: any;
}

declare module 'haul/vendor/polyfills/babelHelpers' {
  declare module.exports: any;
}

declare module 'haul/vendor/polyfills/console' {
  declare module.exports: any;
}

declare module 'haul/vendor/polyfills/error-guard' {
  declare module.exports: any;
}

declare module 'haul/vendor/polyfills/Number.es6' {
  declare module.exports: any;
}

declare module 'haul/vendor/polyfills/Object.es6' {
  declare module.exports: any;
}

declare module 'haul/vendor/polyfills/Object.es7' {
  declare module.exports: any;
}

declare module 'haul/vendor/polyfills/String.prototype.es6' {
  declare module.exports: any;
}

// Filename aliases
declare module 'haul/bin/cli.js' {
  declare module.exports: $Exports<'haul/bin/cli'>;
}
declare module 'haul/hot/index.js' {
  declare module.exports: $Exports<'haul/hot/index'>;
}
declare module 'haul/hot/patch.js' {
  declare module.exports: $Exports<'haul/hot/patch'>;
}
declare module 'haul/src/cli.js' {
  declare module.exports: $Exports<'haul/src/cli'>;
}
declare module 'haul/src/cliEntry.js' {
  declare module.exports: $Exports<'haul/src/cliEntry'>;
}
declare module 'haul/src/commands/bundle.js' {
  declare module.exports: $Exports<'haul/src/commands/bundle'>;
}
declare module 'haul/src/commands/init.js' {
  declare module.exports: $Exports<'haul/src/commands/init'>;
}
declare module 'haul/src/commands/reload.js' {
  declare module.exports: $Exports<'haul/src/commands/reload'>;
}
declare module 'haul/src/commands/start.js' {
  declare module.exports: $Exports<'haul/src/commands/start'>;
}
declare module 'haul/src/errors.js' {
  declare module.exports: $Exports<'haul/src/errors'>;
}
declare module 'haul/src/hot/babelPlugin.js' {
  declare module.exports: $Exports<'haul/src/hot/babelPlugin'>;
}
declare module 'haul/src/hot/client/hotApi.js' {
  declare module.exports: $Exports<'haul/src/hot/client/hotApi'>;
}
declare module 'haul/src/hot/client/hotClient.js' {
  declare module.exports: $Exports<'haul/src/hot/client/hotClient'>;
}
declare module 'haul/src/hot/client/hotPatch.js' {
  declare module.exports: $Exports<'haul/src/hot/client/hotPatch'>;
}
declare module 'haul/src/hot/client/importScriptsPolyfill.js' {
  declare module.exports: $Exports<'haul/src/hot/client/importScriptsPolyfill'>;
}
declare module 'haul/src/hot/client/index.js' {
  declare module.exports: $Exports<'haul/src/hot/client/index'>;
}
declare module 'haul/src/hot/client/utils.js' {
  declare module.exports: $Exports<'haul/src/hot/client/utils'>;
}
declare module 'haul/src/loaders/assetLoader.js' {
  declare module.exports: $Exports<'haul/src/loaders/assetLoader'>;
}
declare module 'haul/src/logger.js' {
  declare module.exports: $Exports<'haul/src/logger'>;
}
declare module 'haul/src/messages/bundleBuilding.js' {
  declare module.exports: $Exports<'haul/src/messages/bundleBuilding'>;
}
declare module 'haul/src/messages/bundleBuilt.js' {
  declare module.exports: $Exports<'haul/src/messages/bundleBuilt'>;
}
declare module 'haul/src/messages/bundleFailed.js' {
  declare module.exports: $Exports<'haul/src/messages/bundleFailed'>;
}
declare module 'haul/src/messages/checkingProject.js' {
  declare module.exports: $Exports<'haul/src/messages/checkingProject'>;
}
declare module 'haul/src/messages/commandFailed.js' {
  declare module.exports: $Exports<'haul/src/messages/commandFailed'>;
}
declare module 'haul/src/messages/commandNotImplemented.js' {
  declare module.exports: $Exports<'haul/src/messages/commandNotImplemented'>;
}
declare module 'haul/src/messages/commandSuccess.js' {
  declare module.exports: $Exports<'haul/src/messages/commandSuccess'>;
}
declare module 'haul/src/messages/editorNotConfigured.js' {
  declare module.exports: $Exports<'haul/src/messages/editorNotConfigured'>;
}
declare module 'haul/src/messages/enterEntryFileName.js' {
  declare module.exports: $Exports<'haul/src/messages/enterEntryFileName'>;
}
declare module 'haul/src/messages/generatedConfig.js' {
  declare module.exports: $Exports<'haul/src/messages/generatedConfig'>;
}
declare module 'haul/src/messages/generatingConfig.js' {
  declare module.exports: $Exports<'haul/src/messages/generatingConfig'>;
}
declare module 'haul/src/messages/gitAddedEntries.js' {
  declare module.exports: $Exports<'haul/src/messages/gitAddedEntries'>;
}
declare module 'haul/src/messages/gitAddingEntries.js' {
  declare module.exports: $Exports<'haul/src/messages/gitAddingEntries'>;
}
declare module 'haul/src/messages/gitAlreadyAdded.js' {
  declare module.exports: $Exports<'haul/src/messages/gitAlreadyAdded'>;
}
declare module 'haul/src/messages/gitNotFound.js' {
  declare module.exports: $Exports<'haul/src/messages/gitNotFound'>;
}
declare module 'haul/src/messages/haulCommandHelp.js' {
  declare module.exports: $Exports<'haul/src/messages/haulCommandHelp'>;
}
declare module 'haul/src/messages/haulHelp.js' {
  declare module.exports: $Exports<'haul/src/messages/haulHelp'>;
}
declare module 'haul/src/messages/index.js' {
  declare module.exports: $Exports<'haul/src/messages/index'>;
}
declare module 'haul/src/messages/initialBundleInformation.js' {
  declare module.exports: $Exports<'haul/src/messages/initialBundleInformation'>;
}
declare module 'haul/src/messages/initialStartInformation.js' {
  declare module.exports: $Exports<'haul/src/messages/initialStartInformation'>;
}
declare module 'haul/src/messages/invalidProject.js' {
  declare module.exports: $Exports<'haul/src/messages/invalidProject'>;
}
declare module 'haul/src/messages/overwriteConfig.js' {
  declare module.exports: $Exports<'haul/src/messages/overwriteConfig'>;
}
declare module 'haul/src/messages/selectEntryFile.js' {
  declare module.exports: $Exports<'haul/src/messages/selectEntryFile'>;
}
declare module 'haul/src/messages/sourceMapFileNotFound.js' {
  declare module.exports: $Exports<'haul/src/messages/sourceMapFileNotFound'>;
}
declare module 'haul/src/messages/sourceMapInvalidFormat.js' {
  declare module.exports: $Exports<'haul/src/messages/sourceMapInvalidFormat'>;
}
declare module 'haul/src/messages/verifiedProject.js' {
  declare module.exports: $Exports<'haul/src/messages/verifiedProject'>;
}
declare module 'haul/src/messages/webpackCompilerPlatformNotFound.js' {
  declare module.exports: $Exports<'haul/src/messages/webpackCompilerPlatformNotFound'>;
}
declare module 'haul/src/messages/webpackConfigNotFound.js' {
  declare module.exports: $Exports<'haul/src/messages/webpackConfigNotFound'>;
}
declare module 'haul/src/resolvers/AssetResolver.js' {
  declare module.exports: $Exports<'haul/src/resolvers/AssetResolver'>;
}
declare module 'haul/src/resolvers/HasteResolver.js' {
  declare module.exports: $Exports<'haul/src/resolvers/HasteResolver'>;
}
declare module 'haul/src/server/assets/debuggerWorker.js' {
  declare module.exports: $Exports<'haul/src/server/assets/debuggerWorker'>;
}
declare module 'haul/src/server/index.js' {
  declare module.exports: $Exports<'haul/src/server/index'>;
}
declare module 'haul/src/server/middleware/devToolsMiddleware.js' {
  declare module.exports: $Exports<'haul/src/server/middleware/devToolsMiddleware'>;
}
declare module 'haul/src/server/middleware/hotMiddleware.js' {
  declare module.exports: $Exports<'haul/src/server/middleware/hotMiddleware'>;
}
declare module 'haul/src/server/middleware/liveReloadMiddleware.js' {
  declare module.exports: $Exports<'haul/src/server/middleware/liveReloadMiddleware'>;
}
declare module 'haul/src/server/middleware/loggerMiddleware.js' {
  declare module.exports: $Exports<'haul/src/server/middleware/loggerMiddleware'>;
}
declare module 'haul/src/server/middleware/missingBundleMiddleware.js' {
  declare module.exports: $Exports<'haul/src/server/middleware/missingBundleMiddleware'>;
}
declare module 'haul/src/server/middleware/openInEditorMiddleware.js' {
  declare module.exports: $Exports<'haul/src/server/middleware/openInEditorMiddleware'>;
}
declare module 'haul/src/server/middleware/rawBodyMiddleware.js' {
  declare module.exports: $Exports<'haul/src/server/middleware/rawBodyMiddleware'>;
}
declare module 'haul/src/server/middleware/requestChangeMiddleware.js' {
  declare module.exports: $Exports<'haul/src/server/middleware/requestChangeMiddleware'>;
}
declare module 'haul/src/server/middleware/statusPageMiddleware.js' {
  declare module.exports: $Exports<'haul/src/server/middleware/statusPageMiddleware'>;
}
declare module 'haul/src/server/middleware/symbolicateMiddleware.js' {
  declare module.exports: $Exports<'haul/src/server/middleware/symbolicateMiddleware'>;
}
declare module 'haul/src/server/middleware/systraceMiddleware.js' {
  declare module.exports: $Exports<'haul/src/server/middleware/systraceMiddleware'>;
}
declare module 'haul/src/server/util/WebsocketDebuggerProxy.js' {
  declare module.exports: $Exports<'haul/src/server/util/WebsocketDebuggerProxy'>;
}
declare module 'haul/src/server/util/websocketProxy.js' {
  declare module.exports: $Exports<'haul/src/server/util/websocketProxy'>;
}
declare module 'haul/src/types.js' {
  declare module.exports: $Exports<'haul/src/types'>;
}
declare module 'haul/src/utils/exec.js' {
  declare module.exports: $Exports<'haul/src/utils/exec'>;
}
declare module 'haul/src/utils/findProvidesModule.js' {
  declare module.exports: $Exports<'haul/src/utils/findProvidesModule'>;
}
declare module 'haul/src/utils/fixRequireIssues.js' {
  declare module.exports: $Exports<'haul/src/utils/fixRequireIssues'>;
}
declare module 'haul/src/utils/getBabelConfig.js' {
  declare module.exports: $Exports<'haul/src/utils/getBabelConfig'>;
}
declare module 'haul/src/utils/getCompilerByPlatform.js' {
  declare module.exports: $Exports<'haul/src/utils/getCompilerByPlatform'>;
}
declare module 'haul/src/utils/getEntryFiles.js' {
  declare module.exports: $Exports<'haul/src/utils/getEntryFiles'>;
}
declare module 'haul/src/utils/getReactNativeVersion.js' {
  declare module.exports: $Exports<'haul/src/utils/getReactNativeVersion'>;
}
declare module 'haul/src/utils/getWebpackConfig.js' {
  declare module.exports: $Exports<'haul/src/utils/getWebpackConfig'>;
}
declare module 'haul/src/utils/haulPortHandler.js' {
  declare module.exports: $Exports<'haul/src/utils/haulPortHandler'>;
}
declare module 'haul/src/utils/haulProgressBar.js' {
  declare module.exports: $Exports<'haul/src/utils/haulProgressBar'>;
}
declare module 'haul/src/utils/makeReactNativeConfig.js' {
  declare module.exports: $Exports<'haul/src/utils/makeReactNativeConfig'>;
}
declare module 'haul/src/utils/polyfillEnvironment.js' {
  declare module.exports: $Exports<'haul/src/utils/polyfillEnvironment'>;
}
declare module 'haul/src/utils/resolveModule.js' {
  declare module.exports: $Exports<'haul/src/utils/resolveModule'>;
}
declare module 'haul/vendor/polyfills/Array.es6.js' {
  declare module.exports: $Exports<'haul/vendor/polyfills/Array.es6'>;
}
declare module 'haul/vendor/polyfills/Array.prototype.es6.js' {
  declare module.exports: $Exports<'haul/vendor/polyfills/Array.prototype.es6'>;
}
declare module 'haul/vendor/polyfills/babelHelpers.js' {
  declare module.exports: $Exports<'haul/vendor/polyfills/babelHelpers'>;
}
declare module 'haul/vendor/polyfills/console.js' {
  declare module.exports: $Exports<'haul/vendor/polyfills/console'>;
}
declare module 'haul/vendor/polyfills/error-guard.js' {
  declare module.exports: $Exports<'haul/vendor/polyfills/error-guard'>;
}
declare module 'haul/vendor/polyfills/Number.es6.js' {
  declare module.exports: $Exports<'haul/vendor/polyfills/Number.es6'>;
}
declare module 'haul/vendor/polyfills/Object.es6.js' {
  declare module.exports: $Exports<'haul/vendor/polyfills/Object.es6'>;
}
declare module 'haul/vendor/polyfills/Object.es7.js' {
  declare module.exports: $Exports<'haul/vendor/polyfills/Object.es7'>;
}
declare module 'haul/vendor/polyfills/String.prototype.es6.js' {
  declare module.exports: $Exports<'haul/vendor/polyfills/String.prototype.es6'>;
}
