// flow-typed signature: c586dfe81c888640b3d6c7c0bb2b06cb
// flow-typed version: <<STUB>>/@appandflow/touchable_v^2.0.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@appandflow/touchable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@appandflow/touchable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@appandflow/touchable/src/__tests__/Touchable-tests' {
  declare module.exports: any;
}

declare module '@appandflow/touchable/src/Touchable' {
  declare module.exports: any;
}

// Filename aliases
declare module '@appandflow/touchable/src/__tests__/Touchable-tests.js' {
  declare module.exports: $Exports<'@appandflow/touchable/src/__tests__/Touchable-tests'>;
}
declare module '@appandflow/touchable/src/Touchable.js' {
  declare module.exports: $Exports<'@appandflow/touchable/src/Touchable'>;
}
